version: "3.7"
services:
  usermgmt:
    build: usermgmt
    network_mode: "host"
  usermgmt_client:
    build: usermgmt_client
    network_mode: "host"
    depends_on:
      - usermgmt_server
  usermgmt_server:
    build: usermgmt_server
    network_mode: "host"
