version: "3.7"
services:
  postgres:
    image: postgres:10.6
    ports:
      - '3002:5432'
    environment:
      POSTGRES_USER: amnon
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dbclient
  rest_api:
    build: login
    ports:
      - "8888:8888"
    network_mode: "host"
    depends_on:
      - usermgmt_client
  usermgmt_client:
    build: client
    ports:
      - "50050:50050"
    network_mode: "host"
    depends_on:
      - usermgmt_server
  usermgmt_server:
    build: server
    ports:
      - "50051:50051"
    network_mode: "host"
    depends_on:
      - usermgmt
  usermgmt:
    build: proto
    network_mode: "host"
    depends_on:
      - postgres