version: "3.7"
services:
  postgres:
    image: postgres:10.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: amnon
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dbclient
  go_mod:
    build: ./
    network_mode: "host"
    depends_on:
      - postgres
  rest_api:
    build: rest_api
    ports:
      - "8888:8888"
    network_mode: "host"
    depends_on:
      - usermgmt_client
  usermgmt_client:
    build: usermgmt_client
    ports:
      - "50050:50050"
    network_mode: "host"
    depends_on:
      - usermgmt
  usermgmt_server:
    build: usermgmt_server
    ports:
      - "50051:50051"
    network_mode: "host"
    depends_on:
      - usermgmt
  usermgmt:
    build: usermgmt
    network_mode: "host"
    depends_on:
      - postgres